name: App Engine Deployment 

on:
  push:
    paths:
      - 'app_engine/**'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch the last two commits to compare changes

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Find changed folder and run script
        run: |
          # Get a list of all changed files
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files:"
          echo "$CHANGED_FILES"

      - name: Check if requirements.in exists
        run: |
          if [ -f requirements.in ]; then
            echo "requirements.in found."
            pip3 install -r requirements.in
          else
            echo "requirements.in not found. Skipping dependency installation."
          fi

      - name: Check if deploy.sh exists and run the script
        run: |
          if [ -f deploy.sh ]; then
            echo "deploy.sh found."
            bash deploy.sh dev
          else
            echo "deploy.sh not found. Skipping deployment."
          fi
