name: App Engine Deployment 

on:
  push:
    paths:
      - 'app_engine/**'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch the last two commits to compare changes

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Find changed folder and run script
        run: |
          # Get a list of all changed files
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files:"
          echo "$CHANGED_FILES"

      - name: Install dependencies
        run: |
          pip install -r requirements.in

      - name: Run the bash script 
        run: |
          bash deploy.sh dev
