name: Run Cloud Functions Script

on:
  push:
    paths:
      - 'cloud_functions/**'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch the last two commits to compare changes

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Find changed folder and run script
        run: |
          # Get a list of all changed files
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          
          # Extract unique directories in the cloud_functions folder
          CHANGED_DIRS=$(echo "$CHANGED_FILES" | grep '^cloud_functions/' | cut -d '/' -f 2 | sort -u)

          if [ -z "$CHANGED_DIRS" ]; then
            echo "No changes detected in any cloud_functions subdirectory."
            exit 0
          fi

          for DIR in $CHANGED_DIRS; do
            echo "Processing directory: cloud_functions/$DIR"
            cd cloud_functions/$DIR
            
            # Install dependencies if requirements.txt exists
            if [ -f "requirements.txt" ]; then
              pip install -r requirements.txt
            fi
            
            # Run the Python script (assuming the main script is named main.py)
            if [ -f "main.py" ]; then
              python main.py
            else
              echo "No main.py script found in $DIR"
            fi

            cd -  # Return to the previous directory
          done
